Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.define :ssslavenode1 do |ssslavenode1|
      ssslavenode1.vm.host_name = "ssslavenode1"
      ssslavenode1.vm.network "private_network", ip:"192.168.12.11"
      ssslavenode1.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "512"]
          vb.customize ["modifyvm", :id, "--cpus", "1"]
      end
	  	config.vm.provision "file", source: "~/ss/staff/hosts", destination: "/vagrant/hosts"
		config.vm.provision "file", source: "~/ss/staff/yum.repos.d.tar.gz", destination: "/vagrant/yum.repos.d.tar.gz"		
	config.vm.provision "shell", path: "~/ss/staff/install.sh"
  end
  
    config.vm.define :ssslavenode2 do |ssslavenode2|
      ssslavenode2.vm.host_name = "ssslavenode2"
      ssslavenode2.vm.network "private_network", ip:"192.168.12.12"
      ssslavenode2.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "512"]
          vb.customize ["modifyvm", :id, "--cpus", "1"]
      end
	  	config.vm.provision "file", source: "~/ss/staff/hosts", destination: "/vagrant/hosts"
		config.vm.provision "file", source: "~/ss/staff/yum.repos.d.tar.gz", destination: "/vagrant/yum.repos.d.tar.gz"		
	config.vm.provision "shell", path: "~/ss/staff/install.sh"
  end
  
  
    config.vm.define :ssslavenode3 do |ssslavenode3|
      ssslavenode3.vm.host_name = "ssslavenode3"
      ssslavenode3.vm.network "private_network", ip:"192.168.12.13"
      ssslavenode3.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "512"]
          vb.customize ["modifyvm", :id, "--cpus", "1"]
      end
	  	config.vm.provision "file", source: "~/ss/staff/hosts", destination: "/vagrant/hosts"
		config.vm.provision "file", source: "~/ss/staff/yum.repos.d.tar.gz", destination: "/vagrant/yum.repos.d.tar.gz"		
	config.vm.provision "shell", path: "~/ss/staff/install.sh"
  end

      config.vm.define :ssmasternode do |ssmasternode|
      ssmasternode.vm.host_name = "ssmasternode"
      ssmasternode.vm.network "private_network", ip:"192.168.12.10"
      ssmasternode.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "1000"]
          vb.customize ["modifyvm", :id, "--cpus", "2"]
      end
	  	config.vm.provision "file", source: "~/ss/staff/hosts", destination: "/vagrant/hosts"
		config.vm.provision "file", source: "~/ss/staff/yum.repos.d.tar.gz", destination: "/vagrant/yum.repos.d.tar.gz"
		config.vm.provision "shell", path: "~/ss/staff/install.sh"
		config.vm.provision "shell", inline: <<-SHELL
			    yum install python-setuptools -y
				easy_install pip
				pip install --upgrade pip
				pip install ansible
					ssh-keyscan -t rsa,dsa ssmasternode 2>&1 | sort -u - ~/.ssh/known_hosts > ~/.ssh/tmp_hosts
					ssh-keyscan -t rsa,dsa ssslavenode1 2>&1 | sort -u - ~/.ssh/known_hosts > ~/.ssh/tmp_hosts
					ssh-keyscan -t rsa,dsa ssslavenode2 2>&1 | sort -u - ~/.ssh/known_hosts > ~/.ssh/tmp_hosts
					ssh-keyscan -t rsa,dsa ssslavenode3 2>&1 | sort -u - ~/.ssh/known_hosts > ~/.ssh/tmp_hosts
					mv ~/.ssh/tmp_hosts ~/.ssh/known_hosts
					


				SHELL
 	#config.vm.provision "shell", path: "~/ss/staff/install.sh"
  end
	
	
  
end
  
