Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  #../staff/



  config.vm.define :ssslavenode1 do |ssslavenode1|
      ssslavenode1.vm.host_name = "ssslavenode1"
      ssslavenode1.vm.network "private_network", ip:"192.168.12.11"
      ssslavenode1.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "512"]
          vb.customize ["modifyvm", :id, "--cpus", "1"]
      end
	  	config.vm.provision "file", source: "../staff/hosts", destination: "/vagrant/hosts"
		config.vm.provision "file", source: "../staff/yum.repos.d.tar.gz", destination: "/vagrant/yum.repos.d.tar.gz"
	config.vm.provision "shell", path: "../staff/install.sh"
  end

    config.vm.define :ssslavenode2 do |ssslavenode2|
      ssslavenode2.vm.host_name = "ssslavenode2"
      ssslavenode2.vm.network "private_network", ip:"192.168.12.12"
      ssslavenode2.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "512"]
          vb.customize ["modifyvm", :id, "--cpus", "1"]
      end
	  	config.vm.provision "file", source: "../staff/hosts", destination: "/vagrant/hosts"
		config.vm.provision "file", source: "../staff/yum.repos.d.tar.gz", destination: "/vagrant/yum.repos.d.tar.gz"
	config.vm.provision "shell", path: "../staff/install.sh"
  end


    config.vm.define :ssslavenode3 do |ssslavenode3|
      ssslavenode3.vm.host_name = "ssslavenode3"
      ssslavenode3.vm.network "private_network", ip:"192.168.12.13"
      ssslavenode3.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "512"]
          vb.customize ["modifyvm", :id, "--cpus", "1"]
      end
	  	config.vm.provision "file", source: "../staff/hosts", destination: "/vagrant/hosts"
		config.vm.provision "file", source: "../staff/yum.repos.d.tar.gz", destination: "/vagrant/yum.repos.d.tar.gz"
	config.vm.provision "shell", path: "../staff/install.sh"
  end



	      config.vm.define :ssmasternode do |ssmasternode|
      ssmasternode.vm.host_name = "ssmasternode"
      ssmasternode.vm.network "private_network", ip:"192.168.12.10"
      ssmasternode.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "1000"]
          vb.customize ["modifyvm", :id, "--cpus", "1"]
      end
	  	config.vm.provision "file", source: "../staff/hosts", destination: "/vagrant/hosts"
		config.vm.provision "file", source: "../staff/yum.repos.d.tar.gz", destination: "/vagrant/yum.repos.d.tar.gz"
		config.vm.provision "shell", path: "../staff/install.sh"

		config.vm.provision "shell", inline: <<-SHELL
		NEWUSER=ansible
		NEWUSERPASS=ansible
			    yum install sshpass python-setuptools -y
				easy_install pip
				pip install --upgrade pip
				pip install ansible
			echo $NEWUSERPASS > /home/$NEWUSER/.ssh/password$NEWUSER.txt
					ssh-keyscan ssmasternode ssslavenode1 ssslavenode2 ssslavenode3 > /home/$NEWUSER/.ssh/known_hosts
					chown -R $NEWUSER:  /home/$NEWUSER/.ssh/*
		sudo -u $NEWUSER sshpass -f /home/$NEWUSER/.ssh/password$NEWUSER.txt  ssh-copy-id $NEWUSER@ssslavenode1
		sudo -u $NEWUSER sshpass -f /home/$NEWUSER/.ssh/password$NEWUSER.txt  ssh-copy-id $NEWUSER@ssslavenode2
		sudo -u $NEWUSER sshpass -f /home/$NEWUSER/.ssh/password$NEWUSER.txt  ssh-copy-id $NEWUSER@ssslavenode3
		sudo -u $NEWUSER sshpass -f /home/$NEWUSER/.ssh/password$NEWUSER.txt  ssh-copy-id $NEWUSER@ssmasternode
		chown -R $NEWUSER:  /home/$NEWUSER/.ssh/*
		updatedb


				SHELL
  end




end
