#!/bin/bash
# Remove-Zabbix Init script should run when an AWS instance goes down and remove itself from Zabbix Server
# chkconfig: - 84 02
# description: Remove from zabbix
# Source function library.
. /etc/init.d/functions

start() {
lockfile=/var/lock/subsys/zabbix-remove
#/bin/touch /var/lock/subsys/Remove-Zabbix
/bin/touch $lockfile

}

stop() {
        /etc/init.d/zabbix-agent stop
        /bin/rm -f $lockfile
        HOST_NAME=`echo $(hostname)`

        USERZ='zabbix'
        PASSZ='ZabbixF0rY0u'
        ZABBIX_SERVER='dell'
        API='http://dell/zabbix/api_jsonrpc.php'

        # Authenticate with Zabbix API

        authenticate() {
                /bin/echo `/usr/bin/curl -s -H  'Content-Type: application/json-rpc' -d "{\"jsonrpc\": \"2.0\",\"method\":\"user.login\",\"params\":{\"user\":\""${USERZ}"\",\"password\":\""${PASSZ}"\"},\"auth\": null,\"id\":0}" $API`
        }

        AUTH_TOKEN=`/bin/echo $(authenticate)|jq -r .result`

        # Get This Host HostId:

        gethostid() {
                /bin/echo `/usr/bin/curl -s -H 'Content-Type: application/json-rpc' -d "{\"jsonrpc\": \"2.0\",\"method\":\"host.get\",\"params\":{\"output\":\"extend\",\"filter\":{\"host\":[\""$HOST_NAME"\"]}},\"auth\":\""${AUTH_TOKEN}"\",\"id\":0}" $API`
        }

        HOST_ID=`echo $(gethostid)|jq -r .result[0].hostid`

        # Remove Host

        remove_host() {
                /bin/echo `/usr/bin/curl -s -H 'Content-Type: application/json-rpc' -d "{\"jsonrpc\": \"2.0\",\"method\":\"host.delete\",\"params\":[\""${HOST_ID}"\"],\"auth\":\""${AUTH_TOKEN}"\",\"id\":0}" $API`
        }
        RESPONSE=$(remove_host)
        /bin/echo ${RESPONSE}
}

case $1 in

        start)
          start
        ;;

        stop)
          stop
        ;;

        restart)
          stop
          start
        ;;

esac
exit 0
